apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-iris-workload
  labels:
    app: demo-iris-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-iris-workload
  template:
    metadata:
      labels:
        app: demo-iris-workload
    spec:
      containers:
      - name: iris-api
        image: us-central1-docker.pkg.dev/my-project-052025/my-repo/iris-api:latest
        ports:
        - containerPort: 8200
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          requests:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"

