name: GCP Artifact Registry Push Debug

on:
  workflow_dispatch:

env:
  IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/iris-api:latest

jobs:
  build-push-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Debug: Print environment and image tag"
        run: |
          echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}"
          echo "GCP_ARTIFACT_REPO: ${{ secrets.GCP_ARTIFACT_REPO }}"
          echo "IMAGE: $IMAGE"
          echo "Proceeding with authentication..."

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: "Debug: Show Docker config"
        run: cat ~/.docker/config.json || echo "No docker config found"

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: List local Docker images
        run: docker images

      - name: Push Docker image to Artifact Registry
        run: docker push $IMAGE









